### PR TITLE
feat: Collect Eligible Roles and Groups from Azure PIM

### PR DESCRIPTION
**Pull request by youduda**
This adds the functionally to collect the eligible roles and eligible groups relations of Azure PIM.
The following Graph API endpoints are used for the collection: [Eligible Roles](https://learn.microsoft.com/en-us/graph/api/rbacapplication-list-roleeligibilityscheduleinstances?view=graph-rest-1.0&tabs=http), [Eligible Groups](https://learn.microsoft.com/en-us/graph/api/privilegedaccessgroup-list-eligibilityscheduleinstances?view=graph-rest-beta). Note: Both endpoints require an explicit admin consent for the required permissions.

The code was tested in a productive environment.

### CODE REVIEW

**Comment by youduda** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by olafhartong** [comment]
This is a great addition! 
I've built a similar implementation in a custom tool. 
On integration for the UI team, please consider adding a edge type similar to GPLink enforced for the Eligible roles so they stand out better

example:
image

**Comment by youduda** [comment]
I already created an implementation for the UI that adds the new edge type similar to what you suggested, see [here](https://github.com/youduda/BloodHound).

**Comment by AlexanderDeBattista** [comment]
Are there any intentions to merge this PR? Have been missing this feature for a long time. :)

**Comment by StephenHinck** [comment]
This PR would require a corroborating BloodHound PR to support adding the new edges. Our team has been working internally on a more fully functional version of this effort, including approvals processes. Expect to see that in the near future.

@youduda - thank you for the contribution. If you would be interested in a swag package, we would happily send you one to show our appreciation. Please email me at shinck [AT] specterops [DOT] io.

**Pull request closed without merging**
