### PR TITLE
feat: Add collection of several new node types

### PR DESCRIPTION
**Pull request by andyrobbins**
Reverts Logic Apps back from being referred to as Workflows

Bifurcates function apps and web apps by keying on "kind" property in response payload

Adds collection for several AzureRM objects:
- Azure Kubernetes Clusters
- Virtual Machine Scale Sets
- Azure Container Registries
- Web Apps

### CODE REVIEW

**Comment by andyrobbins** [comment]
recheck

**Comment by andyrobbins** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ddlees** [comment]
recheck

**Comment by andyrobbins** [comment]
recheck

**Review by ddlees — APPROVED** [review]

**Pull request merged**
