### PR TITLE
Add support for AppRoleAssignments

### PR DESCRIPTION
**Pull request by hugo-syn**
Here is a pull request to retrieve the AppRoleAssigments.

I've added the new *kind* *AZAppRoleAssignment*, it contains the AppRoleAssignment. Nothing else is needed since the AppRole definition can be found in the *AppRoles* attribute of the differents service principals.

It's my first contribution to the project, please do not hesitate to make any comment :)

If it's ok, I could check the Bloodhound repo to add the new node and edge.

### CODE REVIEW

**Comment by ddlees** [comment]
@hugo-syn We are in the process of defining our Contributor License Agreement so that we can accept contributions the "right" way and be the best stewards to the FOSS community that we can be.

Please bear with us while waiting for us to merge this work. From my initial review this contribution looks amazing. Thank you! 😃

**Comment by hugo-syn** [comment]
Alright let me know when it's ok ! :) 

I've also implemented the ingestion and display in BloodHound (https://github.com/BloodHoundAD/BloodHound/pull/578)

**Comment by ddlees** [comment]
recheck

**Comment by ddlees** [comment]
@hugo-syn Would you please consider reading and signing the CLA linked in the comment above? Thank you!

**Comment by ddlees** [comment]
@hugo-syn To fix the tests you should run `go generate ./...`

Alternatively, I can patch things up if you check the setting in this PR that grants me push access to your branch.

image

**Comment by hugo-syn** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by hugo-syn** [comment]
Sorry for the late answer, I've accepted the CLA.  Concerning the "Allow edits by maintainers" button it's already checked :)

**Review by ddlees — APPROVED** [review]
@hugo-syn I made a minor adjustment to the "enriched" `AppRoleAssignment` model to include the associated `AppId`. Otherwise, this looks beautiful! 🥳 

It turns out that each app role is stored on the service principal itself and that `appRoleId` isn't necessarily guaranteed to uniquely represent a specific permission across all apps. Meaning, the app role ID `9e3f62cf-ca93-4989-b6ce-bf83c28f9fe8` that has the `RoleManagement.ReadWrite.Directory` permission in `Microsoft Graph` could represent a totally different permission in another app. Therefore, we need to know both the `appRoleId` and the `appId` so that BloodHound can effectively map abuses.

In any case, thank you very much for your contribution! This work is going to help a great number of people.

**Pull request merged**
